// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web_UI.Models;

#nullable disable

namespace Web_UI.Migrations
{
    [DbContext(typeof(SeoulStayContext))]
    partial class SeoulStayContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Web_UI.Models.AddonService", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("BookingId")
                        .HasColumnType("bigint")
                        .HasColumnName("BookingID");

                    b.Property<long?>("CouponId")
                        .HasColumnType("bigint")
                        .HasColumnName("CouponID");

                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("GUID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("UserID");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("CouponId");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "Guid" }, "UQ_AddonServices_GUID")
                        .IsUnique();

                    b.ToTable("AddonServices");
                });

            modelBuilder.Entity("Web_UI.Models.AddonServiceDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AddonServiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("AddonServiceID");

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("datetime");

                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("GUID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<bool>("IsRefund")
                        .HasColumnType("bit")
                        .HasColumnName("isRefund");

                    b.Property<string>("Notes")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<long>("NumberOfPeople")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<long>("ServiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("ServiceID");

                    b.HasKey("Id");

                    b.HasIndex("AddonServiceId");

                    b.HasIndex("ServiceId");

                    b.HasIndex(new[] { "Guid" }, "UQ_AddonServiceDetails_GUID")
                        .IsUnique();

                    b.ToTable("AddonServiceDetails");
                });

            modelBuilder.Entity("Web_UI.Models.Amenity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("GUID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("IconName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Guid" }, "UQ_Amenities_GUID")
                        .IsUnique();

                    b.ToTable("Amenities");
                });

            modelBuilder.Entity("Web_UI.Models.Area", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("GUID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Guid" }, "UQ_Areas_GUID")
                        .IsUnique();

                    b.ToTable("Areas");
                });

            modelBuilder.Entity("Web_UI.Models.Attraction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("AreaId")
                        .HasColumnType("bigint")
                        .HasColumnName("AreaID");

                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("GUID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex(new[] { "Guid" }, "UQ_Attractions_GUID")
                        .IsUnique();

                    b.ToTable("Attractions");
                });

            modelBuilder.Entity("Web_UI.Models.Booking", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("BookingDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("BookingStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<long>("CancellationPolicyId")
                        .HasColumnType("bigint")
                        .HasColumnName("CancellationPolicyID");

                    b.Property<DateTime>("CheckInDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckOutDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("FinalPrice")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<long>("GuestUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("GuestUserID");

                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("GUID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint")
                        .HasColumnName("ItemID");

                    b.Property<int>("NumberOfGuests")
                        .HasColumnType("int");

                    b.Property<decimal>("PricePerNight")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("SpecialRequests")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<long?>("TransactionId")
                        .HasColumnType("bigint")
                        .HasColumnName("TransactionID");

                    b.HasKey("Id");

                    b.HasIndex("CancellationPolicyId");

                    b.HasIndex("CheckInDate");

                    b.HasIndex("CheckOutDate");

                    b.HasIndex("GuestUserId");

                    b.HasIndex("ItemId");

                    b.HasIndex("TransactionId");

                    b.HasIndex(new[] { "Guid" }, "UQ_Bookings_GUID")
                        .IsUnique();

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Web_UI.Models.BookingCoupon", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AppliedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<long>("BookingId")
                        .HasColumnType("bigint")
                        .HasColumnName("BookingID");

                    b.Property<long>("CouponId")
                        .HasColumnType("bigint")
                        .HasColumnName("CouponID");

                    b.Property<decimal>("DiscountApplied")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("GUID")
                        .HasDefaultValueSql("(newid())");

                    b.HasKey("Id");

                    b.HasIndex("CouponId");

                    b.HasIndex(new[] { "Guid" }, "UQ_BookingCoupons_GUID")
                        .IsUnique();

                    b.HasIndex(new[] { "BookingId", "CouponId" }, "UQ_BookingCoupons_Pair")
                        .IsUnique();

                    b.ToTable("BookingCoupons");
                });

            modelBuilder.Entity("Web_UI.Models.BookingDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BookingId")
                        .HasColumnType("bigint")
                        .HasColumnName("BookingID");

                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("GUID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<bool>("IsRefund")
                        .HasColumnType("bit")
                        .HasColumnName("isRefund");

                    b.Property<long>("ItemPriceId")
                        .HasColumnType("bigint")
                        .HasColumnName("ItemPriceID");

                    b.Property<long?>("RefundCancellationPolicyId")
                        .HasColumnType("bigint")
                        .HasColumnName("RefundCancellationPolicyID");

                    b.Property<DateTime?>("RefundDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("ItemPriceId");

                    b.HasIndex("RefundCancellationPolicyId");

                    b.HasIndex(new[] { "Guid" }, "UQ_BookingDetails_GUID")
                        .IsUnique();

                    b.ToTable("BookingDetails");
                });

            modelBuilder.Entity("Web_UI.Models.BookingStatusHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BookingId")
                        .HasColumnType("bigint")
                        .HasColumnName("BookingID");

                    b.Property<long?>("ChangedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("ChangedByUserID");

                    b.Property<DateTime>("ChangedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("GUID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OldStatus")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex(new[] { "Guid" }, "UQ_BookingStatusHistory_GUID")
                        .IsUnique();

                    b.ToTable("BookingStatusHistory");
                });

            modelBuilder.Entity("Web_UI.Models.CancellationPolicy", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("GUID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PlatformCommissionRate")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Guid" }, "UQ_CancellationPolicies_GUID")
                        .IsUnique();

                    b.ToTable("CancellationPolicies");
                });

            modelBuilder.Entity("Web_UI.Models.CancellationRefundFee", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CancellationPolicyId")
                        .HasColumnType("bigint")
                        .HasColumnName("CancellationPolicyID");

                    b.Property<int>("DaysLeft")
                        .HasColumnType("int");

                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("GUID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<decimal>("PenaltyPercentage")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("Id");

                    b.HasIndex("CancellationPolicyId");

                    b.HasIndex(new[] { "Guid" }, "UQ_CancellationRefundFees_GUID")
                        .IsUnique();

                    b.ToTable("CancellationRefundFees");
                });

            modelBuilder.Entity("Web_UI.Models.Coupon", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CouponCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CurrentUsageCount")
                        .HasColumnType("int");

                    b.Property<decimal>("DiscountPercent")
                        .HasColumnType("decimal(4, 1)");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("GUID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("MaxUsageCount")
                        .HasColumnType("int");

                    b.Property<decimal>("MaximumDiscountAmount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime>("StartDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(CONVERT([date],getdate()))");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CouponCode" }, "UQ_Coupons_CouponCode")
                        .IsUnique();

                    b.HasIndex(new[] { "Guid" }, "UQ_Coupons_GUID")
                        .IsUnique();

                    b.ToTable("Coupons");
                });

            modelBuilder.Entity("Web_UI.Models.DimDate", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("DayName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("DayOfMonth")
                        .HasColumnType("int");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<bool>("IsHoliday")
                        .HasColumnType("bit");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<string>("MonthName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("Quarter")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Date" }, "UQ_DimDates_Date")
                        .IsUnique();

                    b.ToTable("DimDates");
                });

            modelBuilder.Entity("Web_UI.Models.Guest", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("UserID");

                    b.Property<int>("LoyaltyPoints")
                        .HasColumnType("int");

                    b.Property<string>("NationalId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NationalID");

                    b.Property<bool>("NationalIdverified")
                        .HasColumnType("bit")
                        .HasColumnName("NationalIDVerified");

                    b.Property<string>("PreferredLanguage")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("en");

                    b.HasKey("UserId");

                    b.ToTable("Guests");
                });

            modelBuilder.Entity("Web_UI.Models.Host", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("UserID");

                    b.Property<string>("BusinessLicense")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JoinedAsHostDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal?>("Rating")
                        .HasColumnType("decimal(3, 2)");

                    b.Property<string>("TaxCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TotalReviews")
                        .HasColumnType("int");

                    b.Property<DateTime?>("VerifiedDate")
                        .HasColumnType("datetime");

                    b.HasKey("UserId");

                    b.ToTable("Hosts");
                });

            modelBuilder.Entity("Web_UI.Models.HostBankAccount", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AccountHolder")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("GUID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<long>("HostUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("HostUserID");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("HostUserId");

                    b.HasIndex(new[] { "Guid" }, "UQ_HostBankAccounts_GUID")
                        .IsUnique();

                    b.ToTable("HostBankAccounts");
                });

            modelBuilder.Entity("Web_UI.Models.Item", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ApproximateAddress")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<long>("AreaId")
                        .HasColumnType("bigint")
                        .HasColumnName("AreaID");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ExactAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("GUID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("HostRules")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<long>("HostUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("HostUserID");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<long>("ItemTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("ItemTypeID");

                    b.Property<int>("MaximumNights")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(365);

                    b.Property<int>("MinimumNights")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("NumberOfBathrooms")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfBedrooms")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfBeds")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("HostUserId");

                    b.HasIndex("ItemTypeId");

                    b.HasIndex(new[] { "Guid" }, "UQ_Items_GUID")
                        .IsUnique();

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Web_UI.Models.ItemAmenity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AmenityId")
                        .HasColumnType("bigint")
                        .HasColumnName("AmenityID");

                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("GUID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint")
                        .HasColumnName("ItemID");

                    b.HasKey("Id");

                    b.HasIndex("AmenityId");

                    b.HasIndex(new[] { "Guid" }, "UQ_ItemAmenities_GUID")
                        .IsUnique();

                    b.HasIndex(new[] { "ItemId", "AmenityId" }, "UQ_ItemAmenities_Pair")
                        .IsUnique();

                    b.ToTable("ItemAmenities");
                });

            modelBuilder.Entity("Web_UI.Models.ItemAttraction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AttractionId")
                        .HasColumnType("bigint")
                        .HasColumnName("AttractionID");

                    b.Property<decimal?>("Distance")
                        .HasColumnType("decimal(5, 1)");

                    b.Property<int?>("DurationByCar")
                        .HasColumnType("int");

                    b.Property<int?>("DurationOnFoot")
                        .HasColumnType("int");

                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("GUID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint")
                        .HasColumnName("ItemID");

                    b.HasKey("Id");

                    b.HasIndex("AttractionId");

                    b.HasIndex(new[] { "Guid" }, "UQ_ItemAttractions_GUID")
                        .IsUnique();

                    b.HasIndex(new[] { "ItemId", "AttractionId" }, "UQ_ItemAttractions_Pair")
                        .IsUnique();

                    b.ToTable("ItemAttractions");
                });

            modelBuilder.Entity("Web_UI.Models.ItemAvailability", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint")
                        .HasColumnName("ItemID");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex(new[] { "ItemId", "Date" }, "UQ_ItemAvailability_ItemDate")
                        .IsUnique();

                    b.ToTable("ItemAvailability");
                });

            modelBuilder.Entity("Web_UI.Models.ItemPicture", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("GUID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint")
                        .HasColumnName("ItemID");

                    b.Property<string>("PictureFileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex(new[] { "Guid" }, "UQ_ItemPictures_GUID")
                        .IsUnique();

                    b.ToTable("ItemPictures");
                });

            modelBuilder.Entity("Web_UI.Models.ItemPrice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CancellationPolicyId")
                        .HasColumnType("bigint")
                        .HasColumnName("CancellationPolicyID");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("GUID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint")
                        .HasColumnName("ItemID");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Id");

                    b.HasIndex("CancellationPolicyId");

                    b.HasIndex("Date");

                    b.HasIndex(new[] { "Guid" }, "UQ_ItemPrices_GUID")
                        .IsUnique();

                    b.HasIndex(new[] { "ItemId", "Date" }, "UQ_ItemPrices_ItemDate")
                        .IsUnique();

                    b.ToTable("ItemPrices");
                });

            modelBuilder.Entity("Web_UI.Models.ItemScore", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("GUID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint")
                        .HasColumnName("ItemID");

                    b.Property<long>("ScoreId")
                        .HasColumnType("bigint")
                        .HasColumnName("ScoreID");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("UserID");

                    b.Property<long>("Value")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("ScoreId");

                    b.HasIndex(new[] { "Guid" }, "UQ_ItemScores_GUID")
                        .IsUnique();

                    b.HasIndex(new[] { "UserId", "ItemId", "ScoreId" }, "UQ_ItemScores_Pair")
                        .IsUnique();

                    b.ToTable("ItemScores");
                });

            modelBuilder.Entity("Web_UI.Models.ItemType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("GUID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Icon")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Guid" }, "UQ_ItemTypes_GUID")
                        .IsUnique();

                    b.ToTable("ItemTypes");
                });

            modelBuilder.Entity("Web_UI.Models.Review", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BookingId")
                        .HasColumnType("bigint")
                        .HasColumnName("BookingID");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("GUID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<long?>("ItemId")
                        .HasColumnType("bigint")
                        .HasColumnName("ItemID");

                    b.Property<byte>("Rating")
                        .HasColumnType("tinyint");

                    b.Property<long?>("RevieweeId")
                        .HasColumnType("bigint")
                        .HasColumnName("RevieweeID");

                    b.Property<long>("ReviewerId")
                        .HasColumnType("bigint")
                        .HasColumnName("ReviewerID");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("ItemId");

                    b.HasIndex("RevieweeId");

                    b.HasIndex("ReviewerId");

                    b.HasIndex(new[] { "Guid" }, "UQ_Reviews_GUID")
                        .IsUnique();

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Web_UI.Models.Score", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("GUID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Guid" }, "UQ_Scores_GUID")
                        .IsUnique();

                    b.ToTable("Scores");
                });

            modelBuilder.Entity("Web_UI.Models.Service", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BookingCap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L);

                    b.Property<long>("DailyCap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L);

                    b.Property<string>("DayOfMonth")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DayOfWeek")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long?>("Duration")
                        .HasColumnType("bigint");

                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("GUID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<long>("ServiceTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("ServiceTypeID");

                    b.HasKey("Id");

                    b.HasIndex("ServiceTypeId");

                    b.HasIndex(new[] { "Guid" }, "UQ_Services_GUID")
                        .IsUnique();

                    b.ToTable("Services");
                });

            modelBuilder.Entity("Web_UI.Models.ServiceType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("GUID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("IconName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Guid" }, "UQ_ServiceTypes_GUID")
                        .IsUnique();

                    b.ToTable("ServiceTypes");
                });

            modelBuilder.Entity("Web_UI.Models.Transaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("GatewayReturnId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("GatewayReturnID");

                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("GUID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("TransactionTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("TransactionTypeID");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("UserID");

                    b.HasKey("Id");

                    b.HasIndex("TransactionDate");

                    b.HasIndex("TransactionTypeId");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "Guid" }, "UQ_Transactions_GUID")
                        .IsUnique();

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Web_UI.Models.TransactionType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("GUID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Guid" }, "UQ_TransactionTypes_GUID")
                        .IsUnique();

                    b.ToTable("TransactionTypes");
                });

            modelBuilder.Entity("Web_UI.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Country")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte>("Gender")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("GUID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ProfilePicture")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Email" }, "UQ_Users_Email")
                        .IsUnique();

                    b.HasIndex(new[] { "Guid" }, "UQ_Users_GUID")
                        .IsUnique();

                    b.HasIndex(new[] { "Username" }, "UQ_Users_Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Web_UI.Models.VwGuestBookingSummary", b =>
                {
                    b.Property<int?>("CancelledBookings")
                        .HasColumnType("int");

                    b.Property<int?>("CompletedBookings")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("LoyaltyPoints")
                        .HasColumnType("int");

                    b.Property<int?>("TotalBookings")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalSpent")
                        .HasColumnType("decimal(38, 2)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("UserID");

                    b.ToTable((string)null);

                    b.ToView("vw_GuestBookingSummary", (string)null);
                });

            modelBuilder.Entity("Web_UI.Models.VwHostPerformance", b =>
                {
                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("HostUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("HostUserID");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Rating")
                        .HasColumnType("decimal(3, 2)");

                    b.Property<int?>("TotalBookingsReceived")
                        .HasColumnType("int");

                    b.Property<int?>("TotalListings")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalRevenue")
                        .HasColumnType("decimal(38, 2)");

                    b.Property<int>("TotalReviews")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("vw_HostPerformance", (string)null);
                });

            modelBuilder.Entity("Web_UI.Models.VwUserRole", b =>
                {
                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("GuestLoyaltyPoints")
                        .HasColumnType("int");

                    b.Property<decimal?>("HostRating")
                        .HasColumnType("decimal(3, 2)");

                    b.Property<bool?>("HostVerified")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<int>("IsGuest")
                        .HasColumnType("int");

                    b.Property<int>("IsHost")
                        .HasColumnType("int");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("UserID");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.ToTable((string)null);

                    b.ToView("vw_UserRoles", (string)null);
                });

            modelBuilder.Entity("Web_UI.Models.AddonService", b =>
                {
                    b.HasOne("Web_UI.Models.Booking", "Booking")
                        .WithMany("AddonServices")
                        .HasForeignKey("BookingId")
                        .HasConstraintName("FK_AddonServices_Bookings");

                    b.HasOne("Web_UI.Models.Coupon", "Coupon")
                        .WithMany("AddonServices")
                        .HasForeignKey("CouponId")
                        .HasConstraintName("FK_AddonServices_Coupons");

                    b.HasOne("Web_UI.Models.User", "User")
                        .WithMany("AddonServices")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_AddonServices_Users");

                    b.Navigation("Booking");

                    b.Navigation("Coupon");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Web_UI.Models.AddonServiceDetail", b =>
                {
                    b.HasOne("Web_UI.Models.AddonService", "AddonService")
                        .WithMany("AddonServiceDetails")
                        .HasForeignKey("AddonServiceId")
                        .IsRequired()
                        .HasConstraintName("FK_AddonServiceDetails_AddonServices");

                    b.HasOne("Web_UI.Models.Service", "Service")
                        .WithMany("AddonServiceDetails")
                        .HasForeignKey("ServiceId")
                        .IsRequired()
                        .HasConstraintName("FK_AddonServiceDetails_Services");

                    b.Navigation("AddonService");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Web_UI.Models.Attraction", b =>
                {
                    b.HasOne("Web_UI.Models.Area", "Area")
                        .WithMany("Attractions")
                        .HasForeignKey("AreaId")
                        .IsRequired()
                        .HasConstraintName("FK_Attractions_Areas");

                    b.Navigation("Area");
                });

            modelBuilder.Entity("Web_UI.Models.Booking", b =>
                {
                    b.HasOne("Web_UI.Models.CancellationPolicy", "CancellationPolicy")
                        .WithMany("Bookings")
                        .HasForeignKey("CancellationPolicyId")
                        .IsRequired()
                        .HasConstraintName("FK_Bookings_CancellationPolicies");

                    b.HasOne("Web_UI.Models.DimDate", "CheckInDateNavigation")
                        .WithMany("BookingCheckInDateNavigations")
                        .HasForeignKey("CheckInDate")
                        .HasPrincipalKey("Date")
                        .IsRequired()
                        .HasConstraintName("FK_Bookings_CheckInDate_DimDates");

                    b.HasOne("Web_UI.Models.DimDate", "CheckOutDateNavigation")
                        .WithMany("BookingCheckOutDateNavigations")
                        .HasForeignKey("CheckOutDate")
                        .HasPrincipalKey("Date")
                        .IsRequired()
                        .HasConstraintName("FK_Bookings_CheckOutDate_DimDates");

                    b.HasOne("Web_UI.Models.Guest", "GuestUser")
                        .WithMany("Bookings")
                        .HasForeignKey("GuestUserId")
                        .IsRequired()
                        .HasConstraintName("FK_Bookings_Guests");

                    b.HasOne("Web_UI.Models.Item", "Item")
                        .WithMany("Bookings")
                        .HasForeignKey("ItemId")
                        .IsRequired()
                        .HasConstraintName("FK_Bookings_Items");

                    b.HasOne("Web_UI.Models.Transaction", "Transaction")
                        .WithMany("Bookings")
                        .HasForeignKey("TransactionId")
                        .HasConstraintName("FK_Bookings_Transactions");

                    b.Navigation("CancellationPolicy");

                    b.Navigation("CheckInDateNavigation");

                    b.Navigation("CheckOutDateNavigation");

                    b.Navigation("GuestUser");

                    b.Navigation("Item");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("Web_UI.Models.BookingCoupon", b =>
                {
                    b.HasOne("Web_UI.Models.Booking", "Booking")
                        .WithMany("BookingCoupons")
                        .HasForeignKey("BookingId")
                        .IsRequired()
                        .HasConstraintName("FK_BookingCoupons_Bookings");

                    b.HasOne("Web_UI.Models.Coupon", "Coupon")
                        .WithMany("BookingCoupons")
                        .HasForeignKey("CouponId")
                        .IsRequired()
                        .HasConstraintName("FK_BookingCoupons_Coupons");

                    b.Navigation("Booking");

                    b.Navigation("Coupon");
                });

            modelBuilder.Entity("Web_UI.Models.BookingDetail", b =>
                {
                    b.HasOne("Web_UI.Models.Booking", "Booking")
                        .WithMany("BookingDetails")
                        .HasForeignKey("BookingId")
                        .IsRequired()
                        .HasConstraintName("FK_BookingDetails_Bookings");

                    b.HasOne("Web_UI.Models.ItemPrice", "ItemPrice")
                        .WithMany("BookingDetails")
                        .HasForeignKey("ItemPriceId")
                        .IsRequired()
                        .HasConstraintName("FK_BookingDetails_ItemPrices");

                    b.HasOne("Web_UI.Models.CancellationPolicy", "RefundCancellationPolicy")
                        .WithMany("BookingDetails")
                        .HasForeignKey("RefundCancellationPolicyId")
                        .HasConstraintName("FK_BookingDetails_RefundPolicy");

                    b.Navigation("Booking");

                    b.Navigation("ItemPrice");

                    b.Navigation("RefundCancellationPolicy");
                });

            modelBuilder.Entity("Web_UI.Models.BookingStatusHistory", b =>
                {
                    b.HasOne("Web_UI.Models.Booking", "Booking")
                        .WithMany("BookingStatusHistories")
                        .HasForeignKey("BookingId")
                        .IsRequired()
                        .HasConstraintName("FK_BookingStatusHistory_Bookings");

                    b.HasOne("Web_UI.Models.User", "ChangedByUser")
                        .WithMany("BookingStatusHistories")
                        .HasForeignKey("ChangedByUserId")
                        .HasConstraintName("FK_BookingStatusHistory_ChangedByUser");

                    b.Navigation("Booking");

                    b.Navigation("ChangedByUser");
                });

            modelBuilder.Entity("Web_UI.Models.CancellationRefundFee", b =>
                {
                    b.HasOne("Web_UI.Models.CancellationPolicy", "CancellationPolicy")
                        .WithMany("CancellationRefundFees")
                        .HasForeignKey("CancellationPolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CancellationRefundFees_CancellationPolicies");

                    b.Navigation("CancellationPolicy");
                });

            modelBuilder.Entity("Web_UI.Models.Guest", b =>
                {
                    b.HasOne("Web_UI.Models.User", "User")
                        .WithOne("Guest")
                        .HasForeignKey("Web_UI.Models.Guest", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Guests_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Web_UI.Models.Host", b =>
                {
                    b.HasOne("Web_UI.Models.User", "User")
                        .WithOne("Host")
                        .HasForeignKey("Web_UI.Models.Host", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Hosts_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Web_UI.Models.HostBankAccount", b =>
                {
                    b.HasOne("Web_UI.Models.Host", "HostUser")
                        .WithMany("HostBankAccounts")
                        .HasForeignKey("HostUserId")
                        .IsRequired()
                        .HasConstraintName("FK_HostBankAccounts_Hosts");

                    b.Navigation("HostUser");
                });

            modelBuilder.Entity("Web_UI.Models.Item", b =>
                {
                    b.HasOne("Web_UI.Models.Area", "Area")
                        .WithMany("Items")
                        .HasForeignKey("AreaId")
                        .IsRequired()
                        .HasConstraintName("FK_Items_Areas");

                    b.HasOne("Web_UI.Models.Host", "HostUser")
                        .WithMany("Items")
                        .HasForeignKey("HostUserId")
                        .IsRequired()
                        .HasConstraintName("FK_Items_Hosts");

                    b.HasOne("Web_UI.Models.ItemType", "ItemType")
                        .WithMany("Items")
                        .HasForeignKey("ItemTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_Items_ItemTypes");

                    b.Navigation("Area");

                    b.Navigation("HostUser");

                    b.Navigation("ItemType");
                });

            modelBuilder.Entity("Web_UI.Models.ItemAmenity", b =>
                {
                    b.HasOne("Web_UI.Models.Amenity", "Amenity")
                        .WithMany("ItemAmenities")
                        .HasForeignKey("AmenityId")
                        .IsRequired()
                        .HasConstraintName("FK_ItemAmenities_Amenities");

                    b.HasOne("Web_UI.Models.Item", "Item")
                        .WithMany("ItemAmenities")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ItemAmenities_Items");

                    b.Navigation("Amenity");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Web_UI.Models.ItemAttraction", b =>
                {
                    b.HasOne("Web_UI.Models.Attraction", "Attraction")
                        .WithMany("ItemAttractions")
                        .HasForeignKey("AttractionId")
                        .IsRequired()
                        .HasConstraintName("FK_ItemAttractions_Attractions");

                    b.HasOne("Web_UI.Models.Item", "Item")
                        .WithMany("ItemAttractions")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ItemAttractions_Items");

                    b.Navigation("Attraction");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Web_UI.Models.ItemAvailability", b =>
                {
                    b.HasOne("Web_UI.Models.DimDate", "DateNavigation")
                        .WithMany("ItemAvailabilities")
                        .HasForeignKey("Date")
                        .HasPrincipalKey("Date")
                        .IsRequired()
                        .HasConstraintName("FK_ItemAvailability_DimDates");

                    b.HasOne("Web_UI.Models.Item", "Item")
                        .WithMany("ItemAvailabilities")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ItemAvailability_Items");

                    b.Navigation("DateNavigation");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Web_UI.Models.ItemPicture", b =>
                {
                    b.HasOne("Web_UI.Models.Item", "Item")
                        .WithMany("ItemPictures")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ItemPictures_Items");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Web_UI.Models.ItemPrice", b =>
                {
                    b.HasOne("Web_UI.Models.CancellationPolicy", "CancellationPolicy")
                        .WithMany("ItemPrices")
                        .HasForeignKey("CancellationPolicyId")
                        .IsRequired()
                        .HasConstraintName("FK_ItemPrices_CancellationPolicies");

                    b.HasOne("Web_UI.Models.DimDate", "DateNavigation")
                        .WithMany("ItemPrices")
                        .HasForeignKey("Date")
                        .HasPrincipalKey("Date")
                        .IsRequired()
                        .HasConstraintName("FK_ItemPrices_DimDates");

                    b.HasOne("Web_UI.Models.Item", "Item")
                        .WithMany("ItemPrices")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ItemPrices_Items");

                    b.Navigation("CancellationPolicy");

                    b.Navigation("DateNavigation");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Web_UI.Models.ItemScore", b =>
                {
                    b.HasOne("Web_UI.Models.Item", "Item")
                        .WithMany("ItemScores")
                        .HasForeignKey("ItemId")
                        .IsRequired()
                        .HasConstraintName("FK_ItemScores_Items");

                    b.HasOne("Web_UI.Models.Score", "Score")
                        .WithMany("ItemScores")
                        .HasForeignKey("ScoreId")
                        .IsRequired()
                        .HasConstraintName("FK_ItemScores_Scores");

                    b.HasOne("Web_UI.Models.User", "User")
                        .WithMany("ItemScores")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_ItemScores_Users");

                    b.Navigation("Item");

                    b.Navigation("Score");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Web_UI.Models.Review", b =>
                {
                    b.HasOne("Web_UI.Models.Booking", "Booking")
                        .WithMany("Reviews")
                        .HasForeignKey("BookingId")
                        .IsRequired()
                        .HasConstraintName("FK_Reviews_Bookings");

                    b.HasOne("Web_UI.Models.Item", "Item")
                        .WithMany("Reviews")
                        .HasForeignKey("ItemId")
                        .HasConstraintName("FK_Reviews_Items");

                    b.HasOne("Web_UI.Models.User", "Reviewee")
                        .WithMany("ReviewReviewees")
                        .HasForeignKey("RevieweeId")
                        .HasConstraintName("FK_Reviews_Reviewee");

                    b.HasOne("Web_UI.Models.User", "Reviewer")
                        .WithMany("ReviewReviewers")
                        .HasForeignKey("ReviewerId")
                        .IsRequired()
                        .HasConstraintName("FK_Reviews_Reviewer");

                    b.Navigation("Booking");

                    b.Navigation("Item");

                    b.Navigation("Reviewee");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("Web_UI.Models.Service", b =>
                {
                    b.HasOne("Web_UI.Models.ServiceType", "ServiceType")
                        .WithMany("Services")
                        .HasForeignKey("ServiceTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_Services_ServiceTypes");

                    b.Navigation("ServiceType");
                });

            modelBuilder.Entity("Web_UI.Models.Transaction", b =>
                {
                    b.HasOne("Web_UI.Models.DimDate", "TransactionDateNavigation")
                        .WithMany("Transactions")
                        .HasForeignKey("TransactionDate")
                        .HasPrincipalKey("Date")
                        .IsRequired()
                        .HasConstraintName("FK_Transactions_DimDates");

                    b.HasOne("Web_UI.Models.TransactionType", "TransactionType")
                        .WithMany("Transactions")
                        .HasForeignKey("TransactionTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_Transactions_TransactionTypes");

                    b.HasOne("Web_UI.Models.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Transactions_Users");

                    b.Navigation("TransactionDateNavigation");

                    b.Navigation("TransactionType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Web_UI.Models.AddonService", b =>
                {
                    b.Navigation("AddonServiceDetails");
                });

            modelBuilder.Entity("Web_UI.Models.Amenity", b =>
                {
                    b.Navigation("ItemAmenities");
                });

            modelBuilder.Entity("Web_UI.Models.Area", b =>
                {
                    b.Navigation("Attractions");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("Web_UI.Models.Attraction", b =>
                {
                    b.Navigation("ItemAttractions");
                });

            modelBuilder.Entity("Web_UI.Models.Booking", b =>
                {
                    b.Navigation("AddonServices");

                    b.Navigation("BookingCoupons");

                    b.Navigation("BookingDetails");

                    b.Navigation("BookingStatusHistories");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Web_UI.Models.CancellationPolicy", b =>
                {
                    b.Navigation("BookingDetails");

                    b.Navigation("Bookings");

                    b.Navigation("CancellationRefundFees");

                    b.Navigation("ItemPrices");
                });

            modelBuilder.Entity("Web_UI.Models.Coupon", b =>
                {
                    b.Navigation("AddonServices");

                    b.Navigation("BookingCoupons");
                });

            modelBuilder.Entity("Web_UI.Models.DimDate", b =>
                {
                    b.Navigation("BookingCheckInDateNavigations");

                    b.Navigation("BookingCheckOutDateNavigations");

                    b.Navigation("ItemAvailabilities");

                    b.Navigation("ItemPrices");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Web_UI.Models.Guest", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("Web_UI.Models.Host", b =>
                {
                    b.Navigation("HostBankAccounts");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("Web_UI.Models.Item", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("ItemAmenities");

                    b.Navigation("ItemAttractions");

                    b.Navigation("ItemAvailabilities");

                    b.Navigation("ItemPictures");

                    b.Navigation("ItemPrices");

                    b.Navigation("ItemScores");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Web_UI.Models.ItemPrice", b =>
                {
                    b.Navigation("BookingDetails");
                });

            modelBuilder.Entity("Web_UI.Models.ItemType", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Web_UI.Models.Score", b =>
                {
                    b.Navigation("ItemScores");
                });

            modelBuilder.Entity("Web_UI.Models.Service", b =>
                {
                    b.Navigation("AddonServiceDetails");
                });

            modelBuilder.Entity("Web_UI.Models.ServiceType", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("Web_UI.Models.Transaction", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("Web_UI.Models.TransactionType", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Web_UI.Models.User", b =>
                {
                    b.Navigation("AddonServices");

                    b.Navigation("BookingStatusHistories");

                    b.Navigation("Guest");

                    b.Navigation("Host");

                    b.Navigation("ItemScores");

                    b.Navigation("ReviewReviewees");

                    b.Navigation("ReviewReviewers");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
